title: "Welcome to my page!"
author: Tutor
email: sphinx20@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for my blog which will flash your eyes and give you a shock. Watch this space for more updates.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sphinx20 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
