title: Welcome to my page!
author: Tutor
email: sphinx20@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey There!
I am Luxmi. I am trying out this new cool stuff for my students. Let me know how it appears to you. Comments and feedback appreciated!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sphinx20 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
